name=input("enter your name:")
a=int(input("enter your first no :"))
b=int(input("enter your second no :"))
print("summation=",( a+b))
print("subtraction=", (a-b))
print("division=",(a/b))
print("multiplication=",(a*b))
print("reminder=", (a%b))